ARMADA-747 Fix api not sending job script files
omnivector-solutions/jobbergate pull request #130
Opened 2022-08-04 18:18 UTC by fschuch

#### What
A bug was identified after moving the job-script files to S3 (PR #111).

#### Why
As one can see at Jobbergate's source code, the response model for [PendingJobSubmission](https://github.com/omnivector-solutions/jobbergate/blob/3b452eec5fcc6dd5aa33f5907d9f4e13bc1d730a/jobbergate-api/jobbergate_api/apps/job_submissions/schemas.py#L117) does not include the field job_script_data_as_string  anymore. [Cluster-agent](https://github.com/omnivector-solutions/cluster-agent/blob/6b0f576df01f56043dd1df822ae89d314fbaaf99/cluster_agent/jobbergate/schemas.py#L7), of course, expects for it, resulting in an error.

`Task`: https://app.clickup.com/t/18022949/ARMADA-747

---

#### Peer Review
Please follow the upstream omnivector documentation concerning
[peer-review guidelines](https://github.com/omnivector-solutions/Documentation/blob/main/Contributing/pr_review_standards.md#peer-review).

2022-08-04 19:08 UTC, dusktreader commented
Task linked: [ARMADA-747 Jobbergate API is not sending the script files to cluster-agent](https://app.clickup.com/t/18022949/ARMADA-747)

2022-08-05 13:23 UTC, fschuch commented on jobbergate-api/jobbergate_api/apps/job_submissions/routers.py
> +        logger.warning(message)
This should be an error. Also, include the ids the were not found in the error message.

2022-08-05 14:01 UTC, fschuch commented on jobbergate-api/jobbergate_api/apps/job_submissions/routers.py
> +        logger.warning(message)
solved in [90e2940](https://github.com/omnivector-solutions/jobbergate/pull/130/commits/90e29406e5fd144a5c5b394c5cf113140e03d182)

2022-08-08 23:35 UTC, dusktreader requested changes

2022-08-09 12:03 UTC, fschuch commented on jobbergate-api/jobbergate_api/tests/apps/job_submissions/test_routers.py
> +    it is fundamental for the integration with the agent.
solved in [38dfcf3](https://github.com/omnivector-solutions/jobbergate/pull/130/commits/38dfcf3569be9ff47a2bd0973665a46d28b25080)

2022-08-09 12:10 UTC, fschuch commented on jobbergate-api/jobbergate_api/apps/job_submissions/routers.py
> +                job_script_data_as_string=s3man_jobscripts[str(row.get("job_script_id"))],
Do you mean store it in a new variable above?

2022-08-09 12:15 UTC, fschuch commented on jobbergate-api/jobbergate_api/apps/job_submissions/routers.py
> +                job_script_data_as_string=s3man_jobscripts[str(row.get("job_script_id"))],
About the logic on line 328. I choose not to reuse the logic to get an id to report this one is missing. Instead, we loop through all ids again to result in a more informative message.

2022-08-09 17:13 UTC, dusktreader commented on jobbergate-api/jobbergate_api/apps/job_submissions/routers.py
> +                job_script_data_as_string=s3man_jobscripts[str(row.get("job_script_id"))],
Yeah, I mean capture it in a variable and use that on line 323.  I think it could just make the logic a little bit cleaner to read.

2022-08-09 17:14 UTC, dusktreader commented on jobbergate-api/jobbergate_api/apps/job_submissions/routers.py
> +                job_script_data_as_string=s3man_jobscripts[str(row.get("job_script_id"))],
This comment is completely optional. If you are happy with it as is, please just disregard.

2022-08-09 17:14 UTC, dusktreader approved these changes

2022-08-09 18:09 UTC, fschuch commented on jobbergate-api/jobbergate_api/apps/job_submissions/routers.py
> +                job_script_data_as_string=s3man_jobscripts[str(row.get("job_script_id"))],
Thanks for the comments. After some experimentation with different code designs, I would say I'm still happy with this solution.

2022-08-09 18:16 UTC, merged