PENG-2159 Expanded permission sets
omnivector-solutions/jobbergate pull request #523
Opened 2024-04-05 15:39 UTC by dusktreader

Remapped permissions to expand from a view/edit paradigm to individual permissions for create/read/update/delete.

Updated the API with the permission sets.
Updated jobbergate-composed to use the new permission sets.

---

#### Peer Review
Please follow the upstream omnivector documentation concerning
[peer-review guidelines](https://github.com/omnivector-solutions/Documentation/blob/main/Contributing/pr_review_standards.md#peer-review).

2024-04-09 12:48 UTC, fschuch requested changes
Nice work. I left a couple of comments for you.

2024-04-15 15:43 UTC, dusktreader commented on jobbergate-api/jobbergate_api/apps/job_scripts/routers.py
> +    secure_services: SecureService = Depends(secure_services(Permissions.JOB_SCRIPTS_READ, commit=False)),
Is that the only time when you fetch the job_script file, though? Isn't this just a generic endpoint for fetching the file? I worry that adding the other permission would be too limiting for the purpose of this endpoint.

2024-04-15 16:26 UTC, dusktreader commented on jobbergate-composed/etc/jobbergate-local.json
> +          "jobbergate:job-templates:delete"
Addressed in commit 87ff2d0.

2024-04-15 19:44 UTC, fschuch approved these changes

2024-04-15 23:54 UTC, dusktreader commented on jobbergate-api/jobbergate_api/apps/job_scripts/routers.py
> +    secure_services: SecureService = Depends(secure_services(Permissions.JOB_SCRIPTS_READ, commit=False)),
I think we will never have a situation where someone has permission to submit job scripts but does not have permission to see the job scripts that they want to submit from. They will have to have permission to at least see the job scripts to select one to submit.

2024-04-23 22:12 UTC, fschuch approved these changes

2024-04-23 22:17 UTC, merged