PENG-2369 implement the jobbergate agent snap
omnivector-solutions/jobbergate pull request #628
Opened 2024-09-25 15:03 UTC by matheushent

#### What
This PR implement the code base for creating a snap for the Jobbergate Agent. It includes modifications in the actions for running quality assurance against the snap code and for publishing the snap to the *latest/candidate* and *latest/edge* channels.

#### Why
The snap will be used for facilitating the installation of the jobbergate agent.

`Task`: https://sharing.clickup.com/t/h/c/18022949/PENG-2369/RLHZFG26P6LMK8P

---

#### Peer Review
Please follow the upstream omnivector documentation concerning
[peer-review guidelines](https://github.com/omnivector-solutions/Documentation/blob/main/Contributing/pr_review_standards.md#peer-review).

2024-09-25 20:03 UTC, dusktreader requested changes
Nice work! left a few comments for you.

2024-09-26 14:38 UTC, matheushent commented on jobbergate-agent-snap/hooks/bin/configure
> +    snapctl_out: Union[str, None]
answered [here](https://github.com/omnivector-solutions/license-manager/pull/389#discussion_r1777197156)

2024-09-26 14:46 UTC, matheushent commented on jobbergate-agent-snap/hooks/bin/configure
> +def run_bash(bash_string: str) -> str:
done in [e58fa44](https://github.com/omnivector-solutions/jobbergate/pull/628/commits/e58fa44b6abed28d653c2441f78ea2724b5552d8)

2024-09-26 14:46 UTC, matheushent commented on jobbergate-agent-snap/README.md
> +For development purposes, you can build the `jobbergate-agent` part prior of packing the snap. To do that, run:
done in [e58fa44](https://github.com/omnivector-solutions/jobbergate/pull/628/commits/e58fa44b6abed28d653c2441f78ea2724b5552d8)

2024-09-26 14:46 UTC, matheushent commented on jobbergate-agent-snap/README.md
> +- single-user-submitter: The system user name that the agent will use to submit jobs to the SLURM cluster on behalf of in case the *single-user-submitter* is not set. This is optional and defaults to
done in [e58fa44](https://github.com/omnivector-solutions/jobbergate/pull/628/commits/e58fa44b6abed28d653c2441f78ea2724b5552d8)

2024-09-26 14:46 UTC, matheushent commented on jobbergate-agent-snap/README.md
> +This snap requires a few configuration values to be set before it can be used. These values are:
done in [e58fa44](https://github.com/omnivector-solutions/jobbergate/pull/628/commits/e58fa44b6abed28d653c2441f78ea2724b5552d8)

2024-09-26 14:46 UTC, matheushent commented on jobbergate-agent-snap/README.md
> +For installing from the remote store, run:
done in [e58fa44](https://github.com/omnivector-solutions/jobbergate/pull/628/commits/e58fa44b6abed28d653c2441f78ea2724b5552d8)

2024-09-26 14:46 UTC, matheushent commented on jobbergate-agent-snap/Makefile
> +type: ## Run the formatter
fixed in [e58fa44](https://github.com/omnivector-solutions/jobbergate/pull/628/commits/e58fa44b6abed28d653c2441f78ea2724b5552d8)

2024-09-26 15:43 UTC, dusktreader approved these changes

2024-09-26 20:40 UTC, fschuch approved these changes
+1

2024-09-27 13:17 UTC, fschuch approved these changes

2024-09-27 15:48 UTC, dusktreader approved these changes

2024-10-03 18:52 UTC, merged